### ISSUE TITLE
BSN numbers starting with "0" are marked invalid, even though they arent

### ISSUE THREAD

**Issue by peterpeerdeman** [chris-rs/angular-bsn#1]
Hi there,

I was using this module and found out that BSN numbers starting with "0" are marked as incorrect, even though they are correct: https://www.toeslagenaanvragen.net/waar-vind-ik-mijn-bsn/

**Comment by chris-rs** [comment]
Hi Peter,
Just saw this outstanding merge request. Reviewed the fix and merged it! Thanks for the 'leading-0'-fix.
Regards
